//
// Created by DELL on 2019/8/30.
//

#include "Instruction.h"


std::string Instruction::getName() const {
    return _name;
}

InsType Instruction::getType() const {
    return _type;
}

int Instruction::getCycle() const {
    //TODO get cycle via cycle_type
    return _cycle;
}

int Instruction::length() const {
    int result;
    switch (_type) {
        case InsType::IMM:
        case InsType::ZP:
        case InsType::ZPX:
        case InsType::ZPY:
        case InsType::IZX:
        case InsType::IZY:
            result = 2;
            break;
        case InsType::ABS:
        case InsType::ABX:
        case InsType::ABY:
        case InsType::IND:
        case InsType::REL:
            result = 3;
            break;
        case InsType::IMP:
            result = 1;
            break;
    }
    return result;
}

Instruction::Instruction(const char *name, int cycle, InsType type, int cycle_type=0) {
    _name[0] = name[0];
    _name[1] = name[1];
    _name[2] = name[2];
    _name[3] = '\0';
    _cycle = cycle;
    _type = type;
    _cycle_type = cycle_type;
}

const Instruction Instruction::INS[256] = {
        Instruction("BRK", 7, InsType::IMP),
        Instruction("ORA", 6, InsType::IZX),
        Instruction("KIL", 0, InsType::IMM),
        Instruction("SLO", 8, InsType::IZX),
        Instruction("NOP", 3, InsType::ZP),
        Instruction("ORA", 3, InsType::ZP),
        Instruction("ASL", 5, InsType::ZP),
        Instruction("SLO", 5, InsType::ZP),
        Instruction("PHP", 3, InsType::IMP),
        Instruction("ORA", 2, InsType::IMM),
        Instruction("ASL", 2, InsType::IMP),
        Instruction("ANC", 2, InsType::IMM),
        Instruction("NOP", 4, InsType::ABS),
        Instruction("ORA", 4, InsType::ABS),
        Instruction("ASL", 6, InsType::ABS),
        Instruction("SLO", 6, InsType::ABS),
        Instruction("BPL", 2, InsType::REL),
        Instruction("ORA", 5, InsType::IZY),
        Instruction("KIL", 0, InsType::IMM),
        Instruction("SLO", 8, InsType::IZY),
        Instruction("NOP", 4, InsType::ZPX),
        Instruction("ORA", 4, InsType::ZPX),
        Instruction("ASL", 6, InsType::ZPX),
        Instruction("SLO", 6, InsType::ZPX),
        Instruction("CLC", 2, InsType::IMP),
        Instruction("ORA", 4, InsType::ABY),
        Instruction("NOP", 2, InsType::IMP),
        Instruction("SLO", 7, InsType::ABY),
        Instruction("NOP", 4, InsType::ABX),
        Instruction("ORA", 4, InsType::ABX),
        Instruction("ASL", 7, InsType::ABX),
        Instruction("SLO", 7, InsType::ABX),
        Instruction("JSR", 6, InsType::ABS),
        Instruction("AND", 6, InsType::IZX),
        Instruction("KIL", 0, InsType::IMM),
        Instruction("RLA", 8, InsType::IZX),
        Instruction("BIT", 3, InsType::ZP),
        Instruction("AND", 3, InsType::ZP),
        Instruction("ROL", 5, InsType::ZP),
        Instruction("RLA", 5, InsType::ZP),
        Instruction("PLP", 4, InsType::IMP),
        Instruction("AND", 2, InsType::IMM),
        Instruction("ROL", 2, InsType::IMP),
        Instruction("ANC", 2, InsType::IMM),
        Instruction("BIT", 4, InsType::ABS),
        Instruction("AND", 4, InsType::ABS),
        Instruction("ROL", 6, InsType::ABS),
        Instruction("RLA", 6, InsType::ABS),
        Instruction("BMI", 2, InsType::REL),
        Instruction("AND", 5, InsType::IZY),
        Instruction("KIL", 0, InsType::IMM),
        Instruction("RLA", 8, InsType::IZY),
        Instruction("NOP", 4, InsType::ZPX),
        Instruction("AND", 4, InsType::ZPX),
        Instruction("ROL", 6, InsType::ZPX),
        Instruction("RLA", 6, InsType::ZPX),
        Instruction("SEC", 2, InsType::IMP),
        Instruction("AND", 4, InsType::ABY),
        Instruction("NOP", 2, InsType::IMP),
        Instruction("RLA", 7, InsType::ABY),
        Instruction("NOP", 4, InsType::ABX),
        Instruction("AND", 4, InsType::ABX),
        Instruction("ROL", 7, InsType::ABX),
        Instruction("RLA", 7, InsType::ABX),
        Instruction("RTI", 6, InsType::IMP),
        Instruction("EOR", 6, InsType::IZX),
        Instruction("KIL", 0, InsType::IMM),
        Instruction("SRE", 8, InsType::IZX),
        Instruction("NOP", 3, InsType::ZP),
        Instruction("EOR", 3, InsType::ZP),
        Instruction("LSR", 5, InsType::ZP),
        Instruction("SRE", 5, InsType::ZP),
        Instruction("PHA", 3, InsType::IMP),
        Instruction("EOR", 2, InsType::IMM),
        Instruction("LSR", 2, InsType::IMP),
        Instruction("ALR", 2, InsType::IMM),
        Instruction("JMP", 3, InsType::ABS),
        Instruction("EOR", 4, InsType::ABS),
        Instruction("LSR", 6, InsType::ABS),
        Instruction("SRE", 6, InsType::ABS),
        Instruction("BVC", 2, InsType::REL),
        Instruction("EOR", 5, InsType::IZY),
        Instruction("KIL", 0, InsType::IMM),
        Instruction("SRE", 8, InsType::IZY),
        Instruction("NOP", 4, InsType::ZPX),
        Instruction("EOR", 4, InsType::ZPX),
        Instruction("LSR", 6, InsType::ZPX),
        Instruction("SRE", 6, InsType::ZPX),
        Instruction("CLI", 2, InsType::IMP),
        Instruction("EOR", 4, InsType::ABY),
        Instruction("NOP", 2, InsType::IMP),
        Instruction("SRE", 7, InsType::ABY),
        Instruction("NOP", 4, InsType::ABX),
        Instruction("EOR", 4, InsType::ABX),
        Instruction("LSR", 7, InsType::ABX),
        Instruction("SRE", 7, InsType::ABX),
        Instruction("RTS", 6, InsType::IMP),
        Instruction("ADC", 6, InsType::IZX),
        Instruction("KIL", 0, InsType::IMM),
        Instruction("RRA", 8, InsType::IZX),
        Instruction("NOP", 3, InsType::ZP),
        Instruction("ADC", 3, InsType::ZP),
        Instruction("ROR", 5, InsType::ZP),
        Instruction("RRA", 5, InsType::ZP),
        Instruction("PLA", 4, InsType::IMP),
        Instruction("ADC", 2, InsType::IMM),
        Instruction("ROR", 2, InsType::IMP),
        Instruction("ARR", 2, InsType::IMM),
        Instruction("JMP", 5, InsType::IND),
        Instruction("ADC", 4, InsType::ABS),
        Instruction("ROR", 6, InsType::ABS),
        Instruction("RRA", 6, InsType::ABS),
        Instruction("BVS", 2, InsType::REL),
        Instruction("ADC", 5, InsType::IZY),
        Instruction("KIL", 0, InsType::IMM),
        Instruction("RRA", 8, InsType::IZY),
        Instruction("NOP", 4, InsType::ZPX),
        Instruction("ADC", 4, InsType::ZPX),
        Instruction("ROR", 6, InsType::ZPX),
        Instruction("RRA", 6, InsType::ZPX),
        Instruction("SEI", 2, InsType::IMP),
        Instruction("ADC", 4, InsType::ABY),
        Instruction("NOP", 2, InsType::IMP),
        Instruction("RRA", 7, InsType::ABY),
        Instruction("NOP", 4, InsType::ABX),
        Instruction("ADC", 4, InsType::ABX),
        Instruction("ROR", 7, InsType::ABX),
        Instruction("RRA", 7, InsType::ABX),
        Instruction("NOP", 2, InsType::IMM),
        Instruction("STA", 6, InsType::IZX),
        Instruction("NOP", 2, InsType::IMM),
        Instruction("SAX", 6, InsType::IZX),
        Instruction("STY", 3, InsType::ZP),
        Instruction("STA", 3, InsType::ZP),
        Instruction("STX", 3, InsType::ZP),
        Instruction("SAX", 3, InsType::ZP),
        Instruction("DEY", 2, InsType::IMP),
        Instruction("NOP", 2, InsType::IMM),
        Instruction("TXA", 2, InsType::IMP),
        Instruction("XAA", 2, InsType::IMM),
        Instruction("STY", 4, InsType::ABS),
        Instruction("STA", 4, InsType::ABS),
        Instruction("STX", 4, InsType::ABS),
        Instruction("SAX", 4, InsType::ABS),
        Instruction("BCC", 2, InsType::REL),
        Instruction("STA", 6, InsType::IZY),
        Instruction("KIL", 0, InsType::IMM),
        Instruction("AHX", 6, InsType::IZY),
        Instruction("STY", 4, InsType::ZPX),
        Instruction("STA", 4, InsType::ZPX),
        Instruction("STX", 4, InsType::ZPY),
        Instruction("SAX", 4, InsType::ZPY),
        Instruction("TYA", 2, InsType::IMP),
        Instruction("STA", 5, InsType::ABY),
        Instruction("TXS", 2, InsType::IMP),
        Instruction("TAS", 5, InsType::ABY),
        Instruction("SHY", 5, InsType::ABX),
        Instruction("STA", 5, InsType::ABX),
        Instruction("SHX", 5, InsType::ABY),
        Instruction("AHX", 5, InsType::ABY),
        Instruction("LDY", 2, InsType::IMM),
        Instruction("LDA", 6, InsType::IZX),
        Instruction("LDX", 2, InsType::IMM),
        Instruction("LAX", 6, InsType::IZX),
        Instruction("LDY", 3, InsType::ZP),
        Instruction("LDA", 3, InsType::ZP),
        Instruction("LDX", 3, InsType::ZP),
        Instruction("LAX", 3, InsType::ZP),
        Instruction("TAY", 2, InsType::IMP),
        Instruction("LDA", 2, InsType::IMM),
        Instruction("TAX", 2, InsType::IMP),
        Instruction("LAX", 2, InsType::IMM),
        Instruction("LDY", 4, InsType::ABS),
        Instruction("LDA", 4, InsType::ABS),
        Instruction("LDX", 4, InsType::ABS),
        Instruction("LAX", 4, InsType::ABS),
        Instruction("BCS", 2, InsType::REL),
        Instruction("LDA", 5, InsType::IZY),
        Instruction("KIL", 0, InsType::IMM),
        Instruction("LAX", 5, InsType::IZY),
        Instruction("LDY", 4, InsType::ZPX),
        Instruction("LDA", 4, InsType::ZPX),
        Instruction("LDX", 4, InsType::ZPY),
        Instruction("LAX", 4, InsType::ZPY),
        Instruction("CLV", 2, InsType::IMP),
        Instruction("LDA", 4, InsType::ABY),
        Instruction("TSX", 2, InsType::IMP),
        Instruction("LAS", 4, InsType::ABY),
        Instruction("LDY", 4, InsType::ABX),
        Instruction("LDA", 4, InsType::ABX),
        Instruction("LDX", 4, InsType::ABY),
        Instruction("LAX", 4, InsType::ABY),
        Instruction("CPY", 2, InsType::IMM),
        Instruction("CMP", 6, InsType::IZX),
        Instruction("NOP", 2, InsType::IMM),
        Instruction("DCP", 8, InsType::IZX),
        Instruction("CPY", 3, InsType::ZP),
        Instruction("CMP", 3, InsType::ZP),
        Instruction("DEC", 5, InsType::ZP),
        Instruction("DCP", 5, InsType::ZP),
        Instruction("INY", 2, InsType::IMP),
        Instruction("CMP", 2, InsType::IMM),
        Instruction("DEX", 2, InsType::IMP),
        Instruction("AXS", 2, InsType::IMM),
        Instruction("CPY", 4, InsType::ABS),
        Instruction("CMP", 4, InsType::ABS),
        Instruction("DEC", 6, InsType::ABS),
        Instruction("DCP", 6, InsType::ABS),
        Instruction("BNE", 2, InsType::REL),
        Instruction("CMP", 5, InsType::IZY),
        Instruction("KIL", 0, InsType::IMM),
        Instruction("DCP", 8, InsType::IZY),
        Instruction("NOP", 4, InsType::ZPX),
        Instruction("CMP", 4, InsType::ZPX),
        Instruction("DEC", 6, InsType::ZPX),
        Instruction("DCP", 6, InsType::ZPX),
        Instruction("CLD", 2, InsType::IMP),
        Instruction("CMP", 4, InsType::ABY),
        Instruction("NOP", 2, InsType::IMP),
        Instruction("DCP", 7, InsType::ABY),
        Instruction("NOP", 4, InsType::ABX),
        Instruction("CMP", 4, InsType::ABX),
        Instruction("DEC", 7, InsType::ABX),
        Instruction("DCP", 7, InsType::ABX),
        Instruction("CPX", 2, InsType::IMM),
        Instruction("SBC", 6, InsType::IZX),
        Instruction("NOP", 2, InsType::IMM),
        Instruction("ISC", 8, InsType::IZX),
        Instruction("CPX", 3, InsType::ZP),
        Instruction("SBC", 3, InsType::ZP),
        Instruction("INC", 5, InsType::ZP),
        Instruction("ISC", 5, InsType::ZP),
        Instruction("INX", 2, InsType::IMP),
        Instruction("SBC", 2, InsType::IMM),
        Instruction("NOP", 2, InsType::IMP),
        Instruction("SBC", 2, InsType::IMM),
        Instruction("CPX", 4, InsType::ABS),
        Instruction("SBC", 4, InsType::ABS),
        Instruction("INC", 6, InsType::ABS),
        Instruction("ISC", 6, InsType::ABS),
        Instruction("BEQ", 2, InsType::REL),
        Instruction("SBC", 5, InsType::IZY),
        Instruction("KIL", 0, InsType::IMM),
        Instruction("ISC", 8, InsType::IZY),
        Instruction("NOP", 4, InsType::ZPX),
        Instruction("SBC", 4, InsType::ZPX),
        Instruction("INC", 6, InsType::ZPX),
        Instruction("ISC", 6, InsType::ZPX),
        Instruction("SED", 2, InsType::IMP),
        Instruction("SBC", 4, InsType::ABY),
        Instruction("NOP", 2, InsType::IMP),
        Instruction("ISC", 7, InsType::ABY),
        Instruction("NOP", 4, InsType::ABX),
        Instruction("SBC", 4, InsType::ABX),
        Instruction("INC", 7, InsType::ABX),
        Instruction("ISC", 7, InsType::ABX),
};